import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../../components/PageTitle";
import RelatedBlogs from "../../components/RelatedBlogs";
import { BlogItemData } from "../../components/BlogItem";
import { randomNumberFunc } from "../../helpers/randomNumberFunc";

interface Props {
  blog: BlogItemData;
  relatedBlogsData: BlogItemData[];
}

const BlogDetail: NextPage<Props> = ({ blog, relatedBlogsData }) => {
  return (
    <>
      <Head>
        <title>Store - title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={blog.title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={blog.img} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">
                      {blog.category}
                    </span>

                    <span>
                      <span className="cl4">By</span> {blog.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>{blog.date}</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{blog.title}</h4>

                  <p className="stext-117 cl6 p-b-26">{blog.first_content}</p>

                  <p className="stext-117 cl6 p-b-26">{blog.second_content}</p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs data={relatedBlogsData} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default BlogDetail;

export const getStaticPaths: GetStaticPaths = async () => {
  const res = await fetch("http://localhost:5001/blogs");
  const data: BlogItemData[] = await res.json();

  const paths = data.map((prod) => {
    return {
      params: {
        id: prod.id,
      },
    };
  });

  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const id = params?.id;

  if (id) {
    const res = await fetch(`http://localhost:5001/blogs/${id}`);
    const blog: BlogItemData = await res.json();

    const allBlogs = await fetch(`http://localhost:5001/blogs`);
    const allBlogsData: BlogItemData[] = await allBlogs.json();

    const MAX_RANDOM_NUMBER_RELATED_BLOGS = allBlogsData.length - 3;

    const relatedProductsRes = await fetch(
      `http://localhost:5001/blogs?_start=${randomNumberFunc(
        MAX_RANDOM_NUMBER_RELATED_BLOGS
      )}&_limit=3`
    );

    const relatedBlogsData: BlogItemData[] = await relatedProductsRes.json();

    return {
      props: {
        blog,
        relatedBlogsData,
      },
    };
  }

  return {
    notFound: true,
  };
};
