import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner, { BannerInterface } from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import { ProductItemData } from "../components/ProductItem";
import FeaturedProducts from "../components/FeaturedProducts";
import { BlogItemData } from "../components/BlogItem";

interface Props {
  banner_content: BannerInterface;
  featuredProductsData: ProductItemData[];
  blogData: BlogItemData[];
}

const Home: NextPage<Props> = ({
  banner_content,
  featuredProductsData,
  blogData,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner content={banner_content} />

      <CategoryPicker />

      <FeaturedProducts data={featuredProductsData} />

      <FeaturedBlogs data={blogData} />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const bannerRes = await fetch("http://localhost:5001/banner_content");
  const banner_content: BannerInterface = await bannerRes.json();

  const featuredProductsRes = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const featuredProductsData: ProductItemData[] =
    await featuredProductsRes.json();

  const blogRes = await fetch("http://localhost:5001/blogs/?_limit=3");
  const blogData: BlogItemData[] = await blogRes.json();

  return {
    props: {
      banner_content,
      featuredProductsData,
      blogData,
    },
  };
};

export default Home;
